### ISSUE TITLE
CS0426 - The type name 'Web' in the type 'Recaptcha.Web.UI.Controls.Recaptcha' is not available.

### ISSUE THREAD

**Issue by vibetribe** [tanveery/recaptcha-net#14]
Hi there, 

thank you for this great control. It saved some time to me and makes the implementation clean and simple. However, when I try to use any binding expression on your control I get the compiler error on runtime: CS0426 - The type name 'Web' in the type 'Recaptcha.Web.UI.Controls.Recaptcha' is not available.

Example: 

```
<uc:Recaptcha ID="captcha" runat="server" Theme="Blackglass" Language='<%# this.DisplayLanguage %>' />
```

This also happens when I want to bind the public or private key on your control, however, since you allow to set those keys in the web.config, it's not a problem. 

Whatsoever, I could bypass the problem by setting the language in code behind in my Page_Init event: 

```
this.captcha.Language = this.DisplayLanguage;
```

However, it's still a bug, so here I report it.

Thanks for keeping this awesome control up2date.

**Comment by UweKeim** [comment]
Recently, out of nowhere, I'm getting this error on one productin server, too:

> Compiler Error Message: CS0426: The type name 'Web' does not exist in the type 'Recaptcha'
> 
> Source Error:
> 
>     Line 374:            @__activator = System.Web.HttpRuntime.WebObjectActivator;
>     Line 375:            if ((@__activator != null)) {
>     Line 376:                @__ctrl = ((Recaptcha.Web.UI.Controls.Recaptcha)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(Recaptcha.Web.UI.Controls.Recaptcha))));
>     Line 377:            }
>     Line 378:            else {
> 
> Source File: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\shop_15.0\4fad20b7\8193694c\App_Web_login.aspx.4d006ade.7b8rki7g.0.cs    Line: 376 

The website worked for 4+ years, and a recent update with the latest compiled version, brought up this error.

Since the Recaptcha assembly did not change since 4 yeard, I do think some Roslyn update or .NET Framework update is the cause of this.

---------

Further investigation:

Looking at the auto-generated source code .cs file mentioned in the error message above, I first see:

    #line 12 "C:\MyWebsite\Login.aspx"
    using Recaptcha.Web.UI.Controls;

Then, further down the file:

	[System.Diagnostics.DebuggerNonUserCodeAttribute()]
	private global::Recaptcha.Web.UI.Controls.Recaptcha @__BuildControlRecaptcha1() {
	    global::Recaptcha.Web.UI.Controls.Recaptcha @__ctrl;
	    System.IServiceProvider @__activator;
	    @__activator = System.Web.HttpRuntime.WebObjectActivator;
	    if ((@__activator != null)) {
		@__ctrl = ((Recaptcha.Web.UI.Controls.Recaptcha)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(Recaptcha.Web.UI.Controls.Recaptcha))));
	    }
	    else {
		
		#line 44 "C:\MyWebsite\Login.aspx"
		@__ctrl = new global::Recaptcha.Web.UI.Controls.Recaptcha();
		
		#line default
		#line hidden
	    }
	    this.Recaptcha1 = @__ctrl;
	    @__ctrl.ApplyStyleSheetSkin(this);
	    
	    #line 44 "C:\MyWebsite\Login.aspx"
	    @__ctrl.ID = "Recaptcha1";
	    
	    #line default
	    #line hidden
	    return @__ctrl;
	}

As you can see, most of the type usages have the `global::` prefix set, only the one with the errorneous line omits the `global::` prefix.

Since the namespace is the same as the class name, I do think, this is the cause.

-----

### Pragmatic solution

1. I downloaded your source code ZIP here from GitHub
1. I renamed the root namespace to `RecaptchaNetLib`
1. I renamed the assembly to `RecaptchaNetLib.Web`
1. I compiled as a release
1. I removed the NuGet reference in my web application
1. I added a reference to the newly compiled `RecaptchaNetLib.Web` assembly
1. I changed all code-ocurrances to the new namespace

After uploading this to the server, everything again works as expected.

**Comment by UweKeim** [comment]
So on the long run, I would suggest to either change the name of the root namespace or the name of the control to be something different.

**Comment by brogsy** [comment]
I have been using recaptcha-net on an older project without problem, but after some Nuget package updates I now get the following error. Is there likely to be an update for this package?

```
Line 1282:            @__activator = System.Web.HttpRuntime.WebObjectActivator;
Line 1283:            if ((@__activator != null)) {
Line 1284:                @__ctrl = ((Recaptcha.Web.UI.Controls.Recaptcha)(System.Web.HttpRuntime.WebObjectActivator.GetService(typeof(Recaptcha.Web.UI.Controls.Recaptcha))));
Line 1285:            }
Line 1286:            else {
```

**Comment by edika99** [comment]
Same problem Here.
I use recaptcha in 2 project .net 4.7.2  with the same dependencies. In one prject it works perfectly, in the other one give me this error.

**Comment by tanveery** [comment]
Please check out the latest version (3.0.0) of the library. It’s available on NuGet.
